site_name: Libretro Docs
pages:
   - About: index.md
   - Technical:
      - RetroArch:
         - 'Netplay': 'tech/netplay.md'
   - Specifications:
      - 'Libretro': 'specs/api.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
   - Core Library:
      - '2048': 'library/2048.md'
   - Develop:
      - 'Windows': 'compilation/windows.md'
      - 'Nintendo 3DS': 'compilation/3ds.md'
      - 'Nintendo Wii': 'compilation/wii.md'
      - 'Nintendo Wii U': 'compilation/wiiu.md'
      - 'PlayStation3': 'compilation/ps3.md'
      - 'PlayStation Portable': 'compilation/psp.md'
      - 'PlayStation Vita/TV': 'compilation/psvita.md'
   - Tutorials:
      - 'Windows': 'guides/windows.md'
   - Help: help.md
extra:
  logo: 'images/invader.png'
  version: '0.0.2'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'indigo'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
