site_name: Libretro Docs
pages:
   - About: 'index.md'
   - Core Library:
      - '2048': 'library/2048.md'
      - '3DO (4DO)': 'library/4DO.md'
      - 'Atari 2600 (Stella)': 'library/Stella.md'
      - 'Atari Jaguar (Virtual Jaguar)': 'library/Virtual_Jaguar.md'
      - 'Game Boy Advance (gpSP)': 'library/gpsp.md'
      - 'Game Boy Advance (Meteor)': 'library/meteor.md'
      - 'Game Boy Advance (mGBA)': 'library/mgba.md'
      - 'Game Boy Advance (VBA-M)': 'library/vbam.md'
      - 'Game Boy Advance (VBA Next)': 'library/vba_next.md'
      - 'Sega Saturn (Yabause)': 'library/Yabause.md'
      - 'Vectrex (vecx)': 'library/vecx.md'
   - Build RetroArch & Cores:
         - Apple:
            - 'OSX/PowerPC': 'compilation/osxppc.md'
            - 'OSX/macOS': 'compilation/osx.md'
            - 'iOS': 'compilation/ios.md'
         - Linux:
            - 'Ubuntu': 'compilation/ubuntu.md'
         - Microsoft:
            - 'DOS': 'compilation/dos.md'
            - 'Windows 98/2000 (MSVC)': 'compilation/windows98.md'
            - 'Windows XP and later (MSVC)': 'compilation/windowsXP.md'
            - 'Windows Vista and later (MSYS2)': 'compilation/windows.md'
            - 'Xbox': 'compilation/xbox.md'
            - 'Xbox 360': 'compilation/xbox360.md'
         - Nintendo:
            - 'Nintendo 3DS': 'compilation/3ds.md'
            - 'Nintendo GameCube': 'compilation/gamecube.md'
            - 'Nintendo Wii': 'compilation/wii.md'
            - 'Nintendo Wii U': 'compilation/wiiu.md'
         - Sony:
            - 'PlayStation3': 'compilation/ps3.md'
            - 'PlayStation Portable': 'compilation/psp.md'
            - 'PlayStation Vita/TV': 'compilation/psvita.md'
   - Specifications:
      - 'Libretro': 'specs/api.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
   - Technical:
      - RetroArch:
         - 'Netplay': 'tech/netplay.md'
   - Shader Previews:
      - 'Introduction': 'shader/introduction.md'
      - '3dfx': 'shader/3dfx.md'
      - 'antialiasing': 'shader/antialiasing.md'
      - 'border': 'shader/border.md'
      - 'cgp': 'shader/cgp.md'
      - 'crt': 'shader/crt.md'
      - 'cubic': 'shader/cubic.md'
      - 'ddt': 'shader/ddt.md'
      - 'dithering': 'shader/dithering.md'
      - 'eagle': 'shader/eagle.md'
   - User Guides:
      - RetroArch:
         - Getting Started:
           - 'Windows': 'guides/windows.md'
         - Netplay Getting Started / FAQ: 'guides/netplay-faq.md'
   - Help: help.md
extra:
  logo: 'images/invader.png'
  version: '0.0.5'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=Link)
