site_name: Libretro Docs
repo_name: 'libretro/docs'
repo_url: 'https://github.com/libretro/docs'
edit_uri: 'tree/master/docs'
pages:
    - About: 'index.md'
    - Core Library:
      - '2048': 'library/2048.md'
      - '3D Engine': 'library/3d_engine.md'
      - '3DO (4DO)': 'library/4DO.md'
      - 'Arcade (MAME 2003)': 'library/mame2003.md'
      - 'Atari 2600 (Stella)': 'library/Stella.md'
      - 'Atari 7800 (ProSystem)': 'library/prosystem.md'
      - 'Atari Jaguar (Virtual Jaguar)': 'library/virtualjaguar.md'
      - 'Atari Lynx (Beetle Handy)': 'library/beetle_lynx.md'
      - 'Atari Lynx (Handy)': 'library/handy.md'
      - 'Atari ST/STE/TT/Falcon (Hatari)': 'library/hatari.md'
      - 'FFmpeg': 'library/ffmpeg.md'
      - 'Game Boy / Game Boy Color (Emux)': 'library/emux_gb.md'
      - 'Game Boy / Game Boy Color (Gambatte)': 'library/gambatte.md'
      - 'Game Boy / Game Boy Color (SameBoy)': 'library/sameboy.md'
      - 'Game Boy / Game Boy Color (TGB Dual)': 'library/tgbdual.md'
      - 'Game Boy Advance (Beetle GBA)': 'library/beetle_gba.md'
      - 'Game Boy Advance (gpSP)': 'library/gpsp.md'
      - 'Game Boy Advance (Meteor)': 'library/meteor.md'
      - 'Game Boy Advance (mGBA)': 'library/mgba.md'
      - 'Game Boy Advance (VBA-M)': 'library/vbam.md'
      - 'Game Boy Advance (VBA Next)': 'library/vba_next.md'
      - 'Imageviewer': 'library/imageviewer.md'
      - 'MSX/SVI/ColecoVision/SG-1000 (blueMSX)': 'library/bluemsx.md'
      - 'Neo Geo Pocket/Color (Beetle NeoPop)': 'library/beetle_ngp.md'
      - 'NES / Famicom (bnes)': 'library/bnes.md'
      - 'PC Engine/PCE-CD (Beetle PCE FAST)': 'library/beetle_pce_fast.md'
      - 'PC-FX (Beetle PC-FX)': 'library/beetle_pcfx.md'
      - 'PlayStation (Beetle PSX)': 'library/beetle_psx.md'
      - 'PlayStation (Beetle PSX HW)': 'library/beetle_psx_hw.md'
      - 'Sega MS/GG/MD/CD (Genesis Plus GX)': 'library/genesis_plus_gx.md'
      - 'Sega Saturn (Beetle Saturn)': 'library/beetle_saturn.md'
      - 'Sega Saturn (Yabause)': 'library/Yabause.md'
      - 'Vectrex (vecx)': 'library/vecx.md'
      - 'Wonderswan (Color)': 'library/beetle_wswan.md'
      - 'ZX81 (EightyOne)': 'library/eightyone.md'
    - Build RetroArch & Cores:
         - Apple:
            - 'OSX/PowerPC': 'compilation/osxppc.md'
            - 'OSX/macOS': 'compilation/osx.md'
            - 'iOS': 'compilation/ios.md'
         - 'Android': 'compilation/android.md'
         - Linux and BSD:
            - 'Overview for Linux/BSD': 'compilation/linux-and-bsd.md'
            - 'Ubuntu': 'compilation/ubuntu.md'
         - Microsoft:
            - 'DOS': 'compilation/dos.md'
            - Windows NT3.51:
              - 'MSVC Commandline': 'compilation/windowsNT351-msvc-cmdline.md'
            - Windows 95/NT4:
              - 'MSVC Commandline': 'compilation/windows95-msvc-cmdline.md'
            - Windows 98/2000:
              - 'MSVC Commandline': 'compilation/windows98-msvc-cmdline.md'
              - 'MSVC IDE': 'compilation/windows98.md'
            - Windows XP and later:
              - 'MSVC Commandline': 'compilation/windowsXP-msvc-cmdline.md'
              - 'MSVC IDE': 'compilation/windowsXP.md'
            - 'Windows Vista and later (MSYS2)': 'compilation/windows.md'
            - 'Xbox': 'compilation/xbox.md'
            - 'Xbox 360': 'compilation/xbox360.md'
         - Nintendo:
            - 'Nintendo 3DS': 'compilation/3ds.md'
            - 'Nintendo GameCube': 'compilation/gamecube.md'
            - 'Nintendo Wii': 'compilation/wii.md'
            - 'Nintendo Wii U': 'compilation/wiiu.md'
         - Sony:
            - 'PlayStation3': 'compilation/ps3.md'
            - 'PlayStation Portable': 'compilation/psp.md'
            - 'PlayStation Vita/TV': 'compilation/psvita.md'
    - Specifications:
      - 'Libretro': 'specs/api.md'
      - 'RetroPad': 'specs/retropad.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
    - Technical:
      - RetroArch:
         - 'Netplay': 'tech/netplay.md'
         - 'Network Control Interface': 'tech/network-control-interface.md'
    - Shader Previews:
      - 'Introduction': 'shader/introduction.md'
      - '3dfx': 'shader/3dfx.md'
      - 'antialiasing': 'shader/antialiasing.md'
      - 'border': 'shader/border.md'
      - 'cgp': 'shader/cgp.md'
      - 'crt': 'shader/crt.md'
      - 'cubic': 'shader/cubic.md'
      - 'ddt': 'shader/ddt.md'
      - 'dithering': 'shader/dithering.md'
      - 'eagle': 'shader/eagle.md'
      - 'handheld': 'shader/handheld.md'
      - 'handheld-border': 'shader/handheld-border.md'
      - 'hqx': 'shader/hqx.md'
      - 'linear': 'shader/linear.md'
      - 'motionblur': 'shader/motionblur.md'
      - 'mudlord': 'shader/mudlord.md'
      - 'nedi': 'shader/nedi.md'
      - 'nnedi3': 'shader/nnedi3.md'
      - 'ntsc': 'shader/ntsc.md'
      - 'presets': 'shader/presets.md'
      - 'retro': 'shader/retro.md'
      - 'sabr': 'shader/sabr.md'
      - 'scalefx-OLD-shaders': 'shader/scalefx-OLD-shaders.md'
      - 'scalefx': 'shader/scalefx.md'
      - 'scalehq': 'shader/scalehq.md'
      - 'scalenx': 'shader/scalenx.md'
      - 'sharpen': 'shader/sharpen.md'
      - 'windowed': 'shader/windowed.md'
      - 'xbr': 'shader/xbr.md'
      - 'xbrz': 'shader/xbrz.md'
      - 'xsal': 'shader/xsal.md'
      - 'xsoft': 'shader/xsoft.md'
    - Guides:
      - Getting Started:
        - 'Windows': 'guides/windows.md'
        - 'Command-line interface (CLI)': 'guides/cli-intro.md'
        - 'Custom Settings': 'guides/overrides.md'
      - Interface:
        - Creating a Theme: 'guides/themes.md'
        - RGUI Interface: 'guides/RGUI.md'
      - Feature Specific:
        - Input and Joypad Drivers: 'guides/input-joypad-drivers.md'
        - Linux KMS Mode: 'guides/kms-mode.md'
        - Netplay Getting Started / FAQ: 'guides/netplay-faq.md'
        - ROMs, Playlists, and Thumbnails: 'guides/roms-playlists-thumbnails.md'
        - RetroAchievements: 'guides/retroachievements.md'
        - Video Recording and Streaming: 'guides/recording-and-streaming.md'
      - Topics:
        - Optimal Vsync Performance: 'guides/optimal-vsync.md'
        - Softpatching ROMs: 'guides/softpatching.md'
        - Troubleshooting: 'guides/troubleshooting-retroarch.md'
extra:
  logo: 'images/invader.png'
  version: '0.0.5'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=Link)
  - pymdownx.details
