site_name: Libretro Docs
pages:
   - About: 'index.md'
   - Core Library:
      - '2048': 'library/2048.md'
      - '3DO (4DO)': 'library/4DO.md'
      - 'Arcade (MAME 2003)': 'library/mame2003.md'
      - 'Atari 2600 (Stella)': 'library/Stella.md'
      - 'Atari 7800 (ProSystem)': 'library/prosystem.md'
      - 'Atari Jaguar (Virtual Jaguar)': 'library/virtualjaguar.md'
      - 'Atari Lynx (Beetle Handy)': 'library/mednafen_lynx.md'
      - 'Atari Lynx (Handy)': 'library/handy.md'
      - 'Atari ST/STE/TT/Falcon (Hatari)': 'library/hatari.md'
      - 'Game Boy / Game Boy Color (Emux)': 'library/emux_gb.md'
      - 'Game Boy / Game Boy Color (Gambatte)': 'library/gambatte.md'
      - 'Game Boy / Game Boy Color (SameBoy)': 'library/sameboy.md'
      - 'Game Boy / Game Boy Color (TGB Dual)': 'library/tgbdual.md'
      - 'Game Boy Advance (Beetle GBA)': 'library/mednafen_gba.md'
      - 'Game Boy Advance (gpSP)': 'library/gpsp.md'
      - 'Game Boy Advance (Meteor)': 'library/meteor.md'
      - 'Game Boy Advance (mGBA)': 'library/mgba.md'
      - 'Game Boy Advance (VBA-M)': 'library/vbam.md'
      - 'Game Boy Advance (VBA Next)': 'library/vba_next.md'
      - 'MSX/SVI/ColecoVision/SG-1000 (blueMSX)': 'library/bluemsx.md'
      - 'PlayStation (Beetle PSX HW)': 'library/mednafen_psx_hw.md'
      - 'Sega MS/GG/MD/CD (Genesis Plus GX)': 'library/genesis_plus_gx.md'
      - 'Sega Saturn (Yabause)': 'library/Yabause.md'
      - 'Vectrex (vecx)': 'library/vecx.md'
   - Build RetroArch & Cores:
         - Apple:
            - 'OSX/PowerPC': 'compilation/osxppc.md'
            - 'OSX/macOS': 'compilation/osx.md'
            - 'iOS': 'compilation/ios.md'
         - Linux and BSD:
            - 'Overview for Linux/BSD': 'compilation/linux-and-bsd.md'
            - 'Ubuntu': 'compilation/ubuntu.md'
         - Microsoft:
            - 'DOS': 'compilation/dos.md'
            - 'Windows 98/2000 (MSVC)': 'compilation/windows98.md'
            - 'Windows XP and later (MSVC)': 'compilation/windowsXP.md'
            - 'Windows Vista and later (MSYS2)': 'compilation/windows.md'
            - 'Xbox': 'compilation/xbox.md'
            - 'Xbox 360': 'compilation/xbox360.md'
         - Nintendo:
            - 'Nintendo 3DS': 'compilation/3ds.md'
            - 'Nintendo GameCube': 'compilation/gamecube.md'
            - 'Nintendo Wii': 'compilation/wii.md'
            - 'Nintendo Wii U': 'compilation/wiiu.md'
         - Sony:
            - 'PlayStation3': 'compilation/ps3.md'
            - 'PlayStation Portable': 'compilation/psp.md'
            - 'PlayStation Vita/TV': 'compilation/psvita.md'
   - Specifications:
      - 'Libretro': 'specs/api.md'
      - 'RetroPad': specs/retropad.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
   - Technical:
      - RetroArch:
         - 'Netplay': 'tech/netplay.md'
         - 'Network Control Interface': 'tech/network-control-interface.md'
   - Shader Previews:
      - 'Introduction': 'shader/introduction.md'
      - '3dfx': 'shader/3dfx.md'
      - 'antialiasing': 'shader/antialiasing.md'
      - 'border': 'shader/border.md'
      - 'cgp': 'shader/cgp.md'
      - 'crt': 'shader/crt.md'
      - 'cubic': 'shader/cubic.md'
      - 'ddt': 'shader/ddt.md'
      - 'dithering': 'shader/dithering.md'
      - 'eagle': 'shader/eagle.md'
      - 'handheld': 'shader/handheld.md'
      - 'handheld-border': 'shader/handheld-border.md'
      - 'hqx': 'shader/hqx.md'
      - 'linear': 'shader/linear.md'
      - 'motionblur': 'shader/motionblur.md'
      - 'mudlord': 'shader/mudlord.md'
      - 'nedi': 'shader/nedi.md'
      - 'nnedi3': 'shader/nnedi3.md'
      - 'ntsc': 'shader/ntsc.md'
      - 'presets': 'shader/presets.md'
      - 'retro': 'shader/retro.md'
      - 'sabr': 'shader/sabr.md'
      - 'scalefx-OLD-shaders': 'shader/scalefx-OLD-shaders.md'
      - 'scalefx': 'shader/scalefx.md'
      - 'scalehq': 'shader/scalehq.md'
      - 'scalenx': 'shader/scalenx.md'
      - 'sharpen': 'shader/sharpen.md'
      - 'windowed': 'shader/windowed.md'
      - 'xbr': 'shader/xbr.md'
      - 'xbrz': 'shader/xbrz.md'
      - 'xsal': 'shader/xsal.md'
      - 'xsoft': 'shader/xsoft.md'
   - User Guides:
      - RetroArch:
         - Getting Started:
           - 'Windows': 'guides/windows.md'
           - 'Command-line interface (CLI)': 'guides/cli-intro.md'
         - Linux KMS Mode: 'guides/kms-mode.md'
         - Netplay Getting Started / FAQ: 'guides/netplay-faq.md'
         - RGUI Interface: 'guides/RGUI.md'
         - ROMs, Playlists, and Thumbnails: 'guides/roms-playlists-thumbnails.md'
         - Input Drivers: 'guides/input-drivers.md'
         - Getting Optimal Vsync Performance: 'guides/optimal-vsync.md'
         - Troubleshooting: 'guides/troubleshooting-retroarch.md'
         - Creating a Theme: 'guides/themes.md'
         - RetroAchievements: `guides/retroachievements.md`
extra:
  logo: 'images/invader.png'
  version: '0.0.5'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=Link)
