site_name: LibRetro Docs
pages:
   - About: index.md
   - Specifications:
      - 'API': 'specs/api.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
   - Compilation:
      - 'Windows': 'compilation/windows.md'
   - Help: help.md
extra:
  logo: 'images/invader.png'
  version: '0.0.1'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'indigo'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
