site_name: Libretro Docs
pages:
   - About: 'index.md'
   - Core Library:
      - '2048': 'library/2048.md'
      - '3DO (4DO)': 'library/4DO.md'
   - Build RetroArch & Cores:
         - Apple:
            - 'OSX/PowerPC': 'compilation/osxppc.md'
            - 'OSX/macOS': 'compilation/osx.md'
            - 'iOS': 'compilation/ios.md'
         - Linux:
            - 'Ubuntu': 'compilation/ubuntu.md'         
         - Microsoft:
            - 'DOS': 'compilation/dos.md'
            - 'Windows 98/2000 (MSVC)': 'compilation/windows98.md'
            - 'Windows XP and later (MSVC)': 'compilation/windowsXP.md'
            - 'Windows Vista and later (MSYS2)': 'compilation/windows.md'
            - 'Xbox': 'compilation/xbox.md'
            - 'Xbox 360': 'compilation/xbox360.md'
         - Nintendo:
            - 'Nintendo 3DS': 'compilation/3ds.md'
            - 'Nintendo GameCube': 'compilation/gamecube.md'
            - 'Nintendo Wii': 'compilation/wii.md'
            - 'Nintendo Wii U': 'compilation/wiiu.md'
         - Sony:
            - 'PlayStation3': 'compilation/ps3.md'
            - 'PlayStation Portable': 'compilation/psp.md'
            - 'PlayStation Vita/TV': 'compilation/psvita.md'
   - Specifications:
      - 'Libretro': 'specs/api.md'
      - 'Shaders': 'specs/shader.md'
      - 'Overlays': 'specs/overlay.md'
   - Technical:
      - RetroArch:
         - 'Netplay': 'tech/netplay.md'
   - User Guides:
      - RetroArch:
         - Getting Started:
           - 'Windows': 'guides/windows.md'
   - Help: help.md
extra:
  logo: 'images/invader.png'
  version: '0.0.5'
  font:
    text: 'Open Sans'
    code: 'Inconsolata'
  i18n:
    prev: 'Previous'
    next: 'Next'
  palette:
    primary: 'blue'
    accent: 'light blue'
theme: 'material'
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=Link)
